import {
  Archive,
  ArchiveRestore,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  Bell,
  Briefcase,
  Calendar,
  CalendarDays,
  ChartColumn,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  Clapperboard,
  ClipboardList,
  Cloud,
  CloudCheck,
  CloudOff,
  CloudUpload,
  Coins,
  Copy,
  CreditCard,
  Database,
  Delete,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  FileJson,
  FileSpreadsheet,
  Fingerprint,
  Fuel,
  Gift,
  GraduationCap,
  HandCoins,
  HandHelping,
  Handshake,
  HardDrive,
  HeartPulse,
  House,
  Info,
  KeyRound,
  Landmark,
  Laptop,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Minus,
  Moon,
  Palette,
  Pencil,
  Percent,
  Plane,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  RotateCw,
  ScanFace,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  SlidersHorizontal,
  Smartphone,
  Sparkle,
  Sun,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Unplug,
  Upload,
  User,
  Users,
  Utensils,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react-native';

import { useTheme, type iconSize } from '@/theme';

/**
 * Icon names are kebab-case strings, matching the design canvas and the icon
 * keys stored on categories and accounts. Only icons the product uses are
 * mapped, which keeps the bundle to what is drawn and makes an unknown name a
 * type error rather than a blank space.
 */
const icons = {
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'arrow-up-right': ArrowUpRight,
  banknote: Banknote,
  bell: Bell,
  briefcase: Briefcase,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'chart-column': ChartColumn,
  'chart-pie': ChartPie,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dashed': CircleDashed,
  clapperboard: Clapperboard,
  'clipboard-list': ClipboardList,
  cloud: Cloud,
  'cloud-check': CloudCheck,
  'cloud-off': CloudOff,
  'cloud-upload': CloudUpload,
  coins: Coins,
  copy: Copy,
  'credit-card': CreditCard,
  database: Database,
  delete: Delete,
  download: Download,
  ellipsis: Ellipsis,
  eye: Eye,
  'eye-off': EyeOff,
  'file-json': FileJson,
  'file-spreadsheet': FileSpreadsheet,
  fingerprint: Fingerprint,
  fuel: Fuel,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'hand-helping': HandHelping,
  handshake: Handshake,
  'hard-drive': HardDrive,
  'heart-pulse': HeartPulse,
  house: House,
  info: Info,
  'key-round': KeyRound,
  landmark: Landmark,
  laptop: Laptop,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  palette: Palette,
  pencil: Pencil,
  percent: Percent,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'scan-face': ScanFace,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  sparkle: Sparkle,
  sun: Sun,
  tag: Tag,
  target: Target,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  unplug: Unplug,
  upload: Upload,
  user: User,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function isIconName(value: string | null | undefined): value is IconName {
  return typeof value === 'string' && value in icons;
}

type Props = {
  name: IconName;
  /** A size token by context, or an explicit pixel size. */
  size?: keyof typeof iconSize | number;
  /** Defaults to the secondary text colour. Pass a palette value or a category hue. */
  color?: string;
  strokeWidth?: number;
};

/**
 * Thin wrapper over Lucide that fixes the stroke weight at 1.5 and defaults the
 * size by context, so both can change in one place.
 */
export function Icon({ name, size = 'row', color, strokeWidth }: Props) {
  const { palette, iconSize, iconStroke } = useTheme();
  const Glyph = icons[name];
  return (
    <Glyph
      size={typeof size === 'number' ? size : iconSize[size]}
      color={color ?? palette.textSecondary}
      strokeWidth={strokeWidth ?? iconStroke}
      absoluteStrokeWidth={false}
    />
  );
}
